workflows:
  my-workflow:
    instance_type: linux
    cache:
      cache_paths:
        - $HOME/.gradle/caches
    scripts:
      - name: Run unit tests
        script: chmod +x gradlew && ./gradlew test
        test_report: app/build/**/*.xml
      - name: Launch emulator
        script: |
          set -e # exit on first failed command
          cd $ANDROID_HOME/tools
          emulator -avd emulator &
          adb wait-for-device
      - name: Build Android APK
        script: chmod +x gradlew && ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - gillvision0@gmail.com
